Source/Vouzamo.Blog/Models/Domain/Post.cs
using System;
using Vouzamo.Common.Data;

namespace Vouzamo.Blog.Models.Domain
{
    public class Post : IEntity<Guid>
    {
        public Guid Id { get; set; }
        public DateTime PublishDate { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public Guid AuthorId { get; set; }
        public Guid ImageId { get; set; }

        public Post()
        {
            Id = Guid.NewGuid();
            PublishDate = DateTime.Now;
        }

        public Post(string title, string summary, Guid authorId, Guid imageId, DateTime? publishDate = null) : this()
        {
            Title = title;
            Summary = summary;
            AuthorId = authorId;
            ImageId = imageId;

            if (publishDate.HasValue)
            {
                PublishDate = publishDate.Value;
            }
        }
    }
}

Source/Vouzamo.Blog/Areas/Admin/Controllers/PostController.cs
using System;
using System.Web.Mvc;
using Vouzamo.Blog.Data.Commands;
using Vouzamo.Blog.Data.Queries;
using Vouzamo.Blog.Models.Domain;
using Vouzamo.Common.Data;

namespace Vouzamo.Blog.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        protected IQueryDispatcher QueryDispatcher { get; set; }
        protected ICommandDispatcher CommandDispatcher { get; set; }

        public PostController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            QueryDispatcher = queryDispatcher;
            CommandDispatcher = commandDispatcher;
        }

        public ActionResult List(int id =  1)
        {
            var response = QueryDispatcher.Invoke(new AllPostsQuery(id, 12));

            return View(response);
        }

        public ActionResult Create()
        {
            return View(new Post());
        }

        [HttpPost]
        public ActionResult Create(CreatePostCommand model)
        {
            if (ModelState.IsValid)
            {
                var response = CommandDispatcher.Invoke(model);

                return RedirectToAction("List");
            }

            return View(model);
        }

        public ActionResult Edit(Guid id)
        {
            var response = QueryDispatcher.Invoke(new PostByIdQuery(id));

            if (response.Successful)
            {
                return View(response.Response);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit(Post model)
        {
            if (ModelState.IsValid)
            {
                //var response = CommandDispatcher.Invoke(new ChangePostCommand());

                return RedirectToAction("List");
            }

            return View(model);
        }
    }
}

Source/Vouzamo.Blog/Areas/Admin/Controllers/SectionController.cs
using System;
using System.Web.Mvc;
using Vouzamo.Blog.Data.Queries;
using Vouzamo.Blog.Data.Specifications;
using Vouzamo.Blog.Models.Domain;
using Vouzamo.Common.Data;
using Vouzamo.Common.Interop;
using Vouzamo.Common.Specification;

namespace Vouzamo.Blog.Areas.Admin.Controllers
{
    public class SectionController : Controller
    {
        protected IQueryDispatcher QueryDispatcher { get; set; }

        public SectionController(IQueryDispatcher queryDispatcher)
        {
            QueryDispatcher = queryDispatcher;
        }

        public ActionResult List(Guid id)
        {
            var request = QueryDispatcher.Invoke(new AllSectionsQuery(id));

            ViewBag.PostId = id;

            return View(request.Response);
        }

        public ActionResult CreateTextSection(Guid id)
        {
            var request = QueryDispatcher.Invoke(new PostByIdQuery(id));

            if (request.Successful)
            {
                return View(new TextSection() { PostId = id });
            }

            return HttpNotFound();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult CreateTextSection(TextSection model)
        {
            //if (ModelState.IsValid)
            //{
            //    using (var uow = UoWFactory.Create())
            //    {
            //        uow.Repository<Section, Guid>().Create(model);
            //        uow.Commit();
            //    }

            //    return RedirectToAction("Edit", new { id = model.Id });
            //}

            return View(model);
        }
    }
}

Source/Vouzamo.Blog/Controllers/Api/PostController.cs
using System;
using System.Web.Http;
using Vouzamo.Blog.Data.Queries;
using Vouzamo.Blog.Models.Domain;
using Vouzamo.Common.Data;
using Vouzamo.Common.Interop;

namespace Vouzamo.Blog.Controllers.Api
{
    [RoutePrefix("api/post")]
    public class PostsApiController : ApiController
    {
        protected IQueryDispatcher QueryDispatcher { get; set; }

        public PostsApiController(IQueryDispatcher queryDispatcher)
        {
            QueryDispatcher = queryDispatcher;
        }

        [Route("page/{page}"), HttpGet]
        public IManyPagedResponse<Post> Posts(int page)
        {
            return QueryDispatcher.Invoke(new AllPostsQuery(page, 12));
        }

        // This would be better on the Author controller e.g. /author/{id}/posts
        [Route("author/{authorId}/{page}"), HttpGet]
        public IManyResponse<Post> PostsByAuthor(Guid authorId, int page)
        {
            return QueryDispatcher.Invoke(new PostsByAuthorIdQuery(authorId, page, 12));
        }

        [Route("{id}"), HttpGet]
        public ISingleResponse<Post> Post(Guid id)
        {
            return QueryDispatcher.Invoke(new PostByIdQuery(id));
        }

        [Route("{id}/sections"), HttpGet]
        public IManyResponse<Section> PostSections(Guid id)
        {
            return QueryDispatcher.Invoke(new AllSectionsQuery(id));
        }
    }
}

Source/Vouzamo.Blog/Areas/Admin/Views/Post/Create.cshtml
@model Vouzamo.Blog.Models.Domain.Post

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summary, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageId, "ImageId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ImageId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImageId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Source/Vouzamo.Blog/Areas/Admin/Views/Post/Edit.cshtml
@model Vouzamo.Blog.Models.Domain.Post

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summary, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AuthorId, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageId, "ImageId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.ImageId, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImageId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Sections", "List", "Section", new { id = Model.Id }, null)
    @Html.ActionLink("Back to List", "List")
</div>

Source/Vouzamo.Blog/Areas/Admin/Views/Post/List.cshtml
@model Vouzamo.Common.Interop.IManyPagedResponse<Vouzamo.Blog.Models.Domain.Post>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Posts</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th style="width: 10px"></th>
                    <th>Title</th>
                    <th>Summary</th>
                    <th style="width: 40px">Action(s)</th>
                </tr>
                @foreach (var post in Model.Response)
                {
                    <tr>
                        <td></td>
                        <td>@post.Title</td>
                        <td>@post.Summary</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = post.Id })
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="4">
                        @Html.ActionLink("Create", "Create")
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix">
        <ul class="pagination pagination-sm no-margin pull-right">
            @if (Model.HasPreviousPage)
            {
                <li><a href="@Url.Action("List", new {id = Model.PreviousPage})">«</a></li>
            }
            @*<li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>*@
            @if (Model.HasNextPage)
            {
                <li><a href="@Url.Action("List", new { id = Model.NextPage })">»</a></li>
            }
        </ul>
    </div>
</div>
<!-- /.box -->