Source/Vouzamo.Blog/Models/Domain/Post.cs
using System;
using Vouzamo.Common.Data;

namespace Vouzamo.Blog.Models.Domain
{
    public class Post : IEntity<Guid>
    {
        public Guid Id { get; set; }
        public DateTime PublishDate { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public Guid AuthorId { get; set; }
        public Guid ImageId { get; set; }

        public Post()
        {
            Id = Guid.NewGuid();
            PublishDate = DateTime.Now;
        }

        public Post(string title, string summary, Guid authorId, Guid imageId, DateTime? publishDate = null) : this()
        {
            Title = title;
            Summary = summary;
            AuthorId = authorId;
            ImageId = imageId;

            if (publishDate.HasValue)
            {
                PublishDate = publishDate.Value;
            }
        }
    }
}

Source/Vouzamo.Blog/Areas/Admin/Controllers/PostController.cs
using System;
using System.Web.Mvc;
using Vouzamo.Blog.Data.Commands;
using Vouzamo.Blog.Data.Queries;
using Vouzamo.Blog.Models.Domain;
using Vouzamo.Common.Data;

namespace Vouzamo.Blog.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        protected IQueryDispatcher QueryDispatcher { get; set; }
        protected ICommandDispatcher CommandDispatcher { get; set; }

        public PostController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            QueryDispatcher = queryDispatcher;
            CommandDispatcher = commandDispatcher;
        }

        public ActionResult List(int id =  1)
        {
            var response = QueryDispatcher.Invoke(new AllPostsQuery(id, 12));

            return View(response);
        }

        public ActionResult Create()
        {
            return View(new Post());
        }

        [HttpPost]
        public ActionResult Create(CreatePostCommand model)
        {
            if (ModelState.IsValid)
            {
                var response = CommandDispatcher.Invoke(model);

                return RedirectToAction("List");
            }

            return View(model);
        }

        public ActionResult Edit(Guid id)
        {
            var response = QueryDispatcher.Invoke(new PostByIdQuery(id));

            if (response.Successful)
            {
                return View(response.Response);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit(Post model)
        {
            if (ModelState.IsValid)
            {
                //var response = CommandDispatcher.Invoke(new ChangePostCommand());

                return RedirectToAction("List");
            }

            return View(model);
        }
    }
}

Source/Vouzamo.Blog/Controllers/Api/PostController.cs
using System;
using System.Web.Http;
using Vouzamo.Blog.Data.Queries;
using Vouzamo.Blog.Models.Domain;
using Vouzamo.Common.Data;
using Vouzamo.Common.Interop;

namespace Vouzamo.Blog.Controllers.Api
{
    [RoutePrefix("api/post")]
    public class PostsApiController : ApiController
    {
        protected IQueryDispatcher QueryDispatcher { get; set; }

        public PostsApiController(IQueryDispatcher queryDispatcher)
        {
            QueryDispatcher = queryDispatcher;
        }

        [Route("page/{page}"), HttpGet]
        public IManyPagedResponse<Post> Posts(int page)
        {
            return QueryDispatcher.Invoke(new AllPostsQuery(page, 12));
        }

        // This would be better on the Author controller e.g. /author/{id}/posts
        [Route("author/{authorId}/{page}"), HttpGet]
        public IManyResponse<Post> PostsByAuthor(Guid authorId, int page)
        {
            return QueryDispatcher.Invoke(new PostsByAuthorIdQuery(authorId, page, 12));
        }

        [Route("{id}"), HttpGet]
        public ISingleResponse<Post> Post(Guid id)
        {
            return QueryDispatcher.Invoke(new PostByIdQuery(id));
        }

        [Route("{id}/sections"), HttpGet]
        public IManyResponse<Section> PostSections(Guid id)
        {
            return QueryDispatcher.Invoke(new AllSectionsQuery(id));
        }
    }
}

Source/Vouzamo.Blog/Controllers/ComponentController.cs
using System;
using System.Web.Mvc;
using Vouzamo.Blog.Data.Queries;
using Vouzamo.Blog.Data.Specifications;
using Vouzamo.Blog.Models.Domain;
using Vouzamo.Common.Data;
using Vouzamo.Common.Interop;
using Vouzamo.Common.Specification;

namespace Vouzamo.Blog.Controllers
{
    public class ComponentController : Controller
    {
        protected IQueryDispatcher QueryDispatcher { get; set; }

        public ComponentController(IQueryDispatcher queryDispatcher)
        {
            QueryDispatcher = queryDispatcher;
        }

        public ActionResult Posts()
        {
            var request = QueryDispatcher.Invoke(new AllPostsQuery(1, 12));

            return View(request);
        }

        public ActionResult Witticism()
        {
            var query = new SingleResponse<Witticism>(null, false);

            if (query.Successful)
            {
                return View(query.Response);
            }

            return new EmptyResult();
        }

        public ActionResult Author(Guid id)
        {
            var query = QueryDispatcher.Invoke(new AuthorByIdQuery(id));

            return View(query.Response);
        }

        public ActionResult Sections(Guid id)
        {
            var query = QueryDispatcher.Invoke(new AllSectionsQuery(id));

            return View(query);
        }

        public ActionResult BackgroundImage(Guid id)
        {
            var query = QueryDispatcher.Invoke(new ImageByIdQuery(id));

            return View(query.Response);
        }

        public ActionResult Image(Guid id)
        {
            var query = QueryDispatcher.Invoke(new ImageByIdQuery(id));

            return View(query.Response);
        }
    }
}

Source/Vouzamo.Blog/Controllers/HomeController.cs
using System;
using System.Web.Mvc;
using Vouzamo.Blog.Data.Queries;
using Vouzamo.Blog.Models.Domain;
using Vouzamo.Common.Data;

namespace Vouzamo.Blog.Controllers
{
    public class HomeController : Controller
    {
        protected IQueryDispatcher QueryDispatcher { get; set; }

        public HomeController(IQueryDispatcher queryDispatcher)
        {
            QueryDispatcher = queryDispatcher;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }

        public ActionResult Posts(int id)
        {
            var results = QueryDispatcher.Invoke(new AllPostsQuery(id, 12));

            return View(results);
        }

        public ActionResult Post(Guid id)
        {
            var query = QueryDispatcher.Invoke(new PostByIdQuery(id));

            if (query.Successful)
            {
                return View(query.Response);
            }

            return HttpNotFound();
        }
    }
}

Source/Vouzamo.Blog/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    @Html.Action("Posts", "Component")
</div>

Source/Vouzamo.Blog/Views/Home/Post.cshtml
@using Vouzamo.Blog.Models.Domain

@model Post

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Header
{
    <header class="intro-header" style="background-image: url('@Html.Action("BackgroundImage", "Component", new { id = Model.ImageId }).ToString().Trim()')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>@Model.Title</h1>
                        @if (!string.IsNullOrWhiteSpace(Model.Summary))
                        {
                            <h2 class="subheading">@Model.Summary</h2>
                        }
                        <span class="meta">
                            by @Html.Action("Author", "Component", new { id = Model.AuthorId }) on @Model.PublishDate.ToLongDateString()
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
}

@Html.Action("Sections", "Component", new { id = Model.Id })

Source/Vouzamo.Blog/Views/Home/Posts.cshtml
@using Vouzamo.Blog.Models.Domain

@model Vouzamo.Common.Interop.IManyPagedResponse<Post>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Header
{
    <header class="intro-header" style="background-image: url('/Static/Images/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Posts</h1>
                        <hr class="small">
                    </div>
                </div>
            </div>
        </div>
    </header>
}

<div class="row">
    @Html.Partial("~/Views/Component/Posts.cshtml", Model)
</div>